---

fail_fast: false
ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - name: (code) -- check end of file
        id: end-of-file-fixer
      - name: (code) -- check trailing space
        id: trailing-whitespace
      - name: (syntax) -- check yaml
        id: check-yaml
      - name: (syntax) -- check json
        id: check-json
      - name: (syntax) -- check xml
        id: check-xml
      - name: (syntax) -- check toml
        id: check-toml
      - name: (file) -- check case conflict
        id: check-case-conflict
      - name: (file) -- check symlinks
        id: check-symlinks
      - name: (file) -- check destroyed symlinks
        id: destroyed-symlinks
      - name: (security) -- detect private key
        id: detect-private-key

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.2
    hooks:
      - name: (bitbucket-pipelines) -- check bitbucket-pipelines syntax
        id: check-bitbucket-pipelines
      - name: (github-dependabot) -- check github-dependabot syntax
        id: check-dependabot
      - name: (github-actions) -- check github-actions syntax
        id: check-github-workflows

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.27
    hooks:
      - name: (github-actions) - lint github actions
        id: actionlint


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - name: (python) -- check requirements-txt
        id: requirements-txt-fixer
      - name: (python) -- check syntax with ast
        id: check-ast

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - name: (python) -- check syntax with ruff
        id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ -n, --fix ]
      - name: (python) -- format files with ruff
        id: ruff-format
        args: [ -n ]
        types_or: [ python, pyi, jupyter ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - name: (git) -- no commit to branch
        id: no-commit-to-branch
      - name: (git) -- check merge conflicts
        id: check-merge-conflict
